### ISSUE TITLE
Joining shared activity causes activity to not start

### ISSUE THREAD

**Issue by quozl** [sugarlabs/sugar-toolkit-gtk3#406]
Reproducer: share the Chat activity from another system, then attempt to join it,

Expected result: activity starts.

Observed result: activity does not start, and logs contain a traceback;

```
Traceback (most recent call last):
  File "/usr/bin/sugar-activity", line 5, in <module>
    activityinstance.main()
  File "/usr/lib/python2.7/dist-packages/sugar3/activity/activityinstance.py", line 219, in main
    instance = create_activity_instance(activity_constructor, activity_handle)
  File "/usr/lib/python2.7/dist-packages/sugar3/activity/activityinstance.py", line 50, in create_activity_instance
    activity = constructor(handle)
  File "/usr/share/sugar/activities/Chat.activity/activity.py", line 86, in __init__
    super(Chat, self).__init__(handle)
  File "/usr/lib/python2.7/dist-packages/sugar3/activity/activity.py", line 436, in __init__
    warn_if_none=False)
  File "/usr/lib/python2.7/dist-packages/sugar3/presence/presenceservice.py", line 104, in get_activity
    room_handle=room_handle)
  File "/usr/lib/python2.7/dist-packages/sugar3/presence/activity.py", line 124, in __init__
    self._start_tracking_properties()
  File "/usr/lib/python2.7/dist-packages/sugar3/presence/activity.py", line 140, in _start_tracking_properties
    arg_dict)
TypeError: call_async() takes at least 9 arguments (8 given)
```

Seen on upgrade to Sugar 0.113.

@pro-panda, was your change to `_start_tracking_properties` tested?

**Comment by pro-panda** [comment]
I'm not sure. 

Reason for the [change](https://github.com/sugarlabs/sugar-toolkit-gtk3/commit/aa8a5e70c415e6c2acf4ff373d9b366ac4692bb1#diff-03de8f54944bb6037c70d8ec36f91c15R128) was that `utf8_strings` is not an argument in `call_async` Python 3.

**Comment by quozl** [comment]
Thanks.  I've a fix in my branch.  It looks like you were trying to use a `dict` for the keyword arguments.  I've not seen this before.
